id: P36886F08
initial_creation_type: ocr
source_metadata:
  volumes:
    c163cd78c62c44408a5a3b291aeadd6c:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
